export enum ActionTypes {
    SET_LOADING = "SET_LOADING",
    GET_GAME = "GET_GAME",
    GET_GAMES = "GET_GAMES",
    SEARCH_GAMES = "SEARCH_GAMES",
    LOAD_FAVORITES = "LOAD_FAVORITES",
    LIKE_GAME = "LIKE_GAME",
    DISLIKE_GAME = "DISLIKE_GAME"
}
